Admin latest
ordinaryCoder/reacted-admin-fe pull request #4
Opened 2022-12-19 10:37 UTC by abhimanyuPatil

2022-12-19 10:39 UTC, abhishek211995 approved these changes

2022-12-21 06:51 UTC, ordinaryCoder requested changes
Please remove typescript  from the validators file

2022-12-21 06:55 UTC, ordinaryCoder commented on src/utils/validators.js
> +export const requiredMessage = (fieldName: string) =>
remove typrescript

2022-12-21 07:08 UTC, ordinaryCoder approved these changes

2022-12-21 07:09 UTC, merged